# Generated by Django 3.0.4 on 2020-06-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('minimum_price', models.FloatField(default=0.0, verbose_name='Precio minimo')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'db_table': 'Marcas',
                'ordering': ['-created_date'],
            },
        ),
    ]
